-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS school CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS results CASCADE;

CREATE TABLE public.student
(
    "OUTID" character varying(255) NOT NULL,
    birth integer NOT NULL,
    sex character varying(255) NOT NULL,
    territory character varying(255) NOT NULL,
    area character varying(255) NOT NULL,
    region character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    class_profile character varying(255),
    class_lang character varying(255),
    school_name character varying(255),
    PRIMARY KEY ("OUTID")
);

CREATE TABLE public.school
(
    school_name character varying(255) NOT NULL,
    school_type character varying(255),
    school_territory character varying(255) NOT NULL,
    school_area character varying(255) NOT NULL,
    school_region character varying(255) NOT NULL,
    school_parent character varying(255),
    PRIMARY KEY (school_name)
);

CREATE TABLE public.locations
(
    territory character varying(255) NOT NULL,
    area character varying(255) NOT NULL,
    region character varying(255) NOT NULL,
    ter_type character varying(255),
    PRIMARY KEY (area, region, territory)
);

CREATE TABLE public.results
(
    "OUTID" character varying(255) NOT NULL,
    subject_name character varying(255) NOT NULL,
    subject_lang character varying(255),
    subject_test_status character varying(255),
    subject_ball100 integer,
    subject_ball12 integer,
    subject_ball integer,
    subject_adapt_scale integer,
    school_name character varying(255) NOT NULL,
    subject_year integer NOT NULL,
    subject_dpa character varying(255),
    PRIMARY KEY ("OUTID", subject_name, subject_year)
);

ALTER TABLE public.results
    ADD FOREIGN KEY ("OUTID")
    REFERENCES public.student ("OUTID")
    NOT VALID;


ALTER TABLE public.results
    ADD FOREIGN KEY (school_name)
    REFERENCES public.school (school_name)
    NOT VALID;


ALTER TABLE public.student
    ADD FOREIGN KEY (territory, area, region)
    REFERENCES public.locations (territory, area, region)
    NOT VALID;


ALTER TABLE public.student
    ADD FOREIGN KEY (school_name)
    REFERENCES public.school (school_name)
    NOT VALID;

END;